development:
  adapter: postgresql
  database: sql_pql_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sql_pql_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d43f44tu4ftjmr
  pool: 5
  timeout: 5000
	user:	eqcyuzdzpnoqdy
	port:	5432
	password: rr08KUBAmFfhYam2liTYFjyyfw